/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FECoreKernel.h>
#include "FECFDDamageFiber.h"
#include "FECFDDamageFiberPlot.h"
#include "version.h"

FECORE_EXPORT unsigned int GetSDKVersion()
{
	return FE_SDK_VERSION;
}

FECORE_EXPORT void GetPluginVersion(int& major, int& minor, int& patch)
{
	major = VERSION;
	minor = SUBVERSION;
	patch = SUBSUBVERSION;
}

FECORE_EXPORT void PluginInitialize(FECoreKernel& febio)
{
	FECoreKernel::SetInstance(&febio);
	febio.SetActiveModule("solid");
	REGISTER_FECORE_CLASS(FECFDDamageFiber, "cfd damage-fiber");

	REGISTER_FECORE_CLASS(FEFiberStretchCriterion, "fiber stretch");
	REGISTER_FECORE_CLASS(FEFiberStrainCriterion, "fiber strain");
	REGISTER_FECORE_CLASS(FEFiberStressCriterion, "fiber stress");

	REGISTER_FECORE_CLASS(FEPlotCFDFiberDamage, "cfd fiber damage");

	REGISTER_FECORE_CLASS(FEDeltaDamageCDF, "CDF delta");
}
